# docker/Dockerfile.fetch
FROM golang:1.22-alpine AS builder
RUN apk add --no-cache git
WORKDIR /app
COPY go.mod ./
RUN go mod download
COPY cmd/fetch-octa ./cmd/fetch-octa
COPY utils ./utils

# Compila binário estático
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 \
    go build -ldflags="-s -w" -o /fetch-octa ./cmd/fetch-octa

# Imagem final
FROM alpine:3.18
RUN apk add --no-cache ca-certificates
COPY --from=builder /fetch-octa /usr/local/bin/fetch-octa
ENTRYPOINT ["fetch-octa"]
